package com.test.exception;

public class TestDemoException {
	// static ArithmeticException e=new ArithmeticException();
	public static void main(String[] args) throws CustomException {
		// for(int j = 1; j<=10; j++) {
		// System.out.println("J "+j);
		// for(int i = 1; i<=10; i++) {
		// if(i%2 == 0) {
		// System.out.println("breaking "+i);
		// break;
		// }
		// System.out.println(i);
		// }
		// if(j == 4) {
		// System.out.println("breaking "+j);
		// break;
		// }
		// }
		// if(a<b) {
		// throw new CustomException("a value should be greater than b");
		// }
		// if(a<b) {
		// throw new CustomException();
		// }
		// TODO Auto-generated method stub
		// System.out.println("State - 1");

		System.out.println(foo1(11));
	}

	public static void foo() {
		//foo1();
	}

	public static int foo1(int b) {
try {
	System.out.println("try");
	int a = 10/0;

	return 5;
} catch (Exception e) {
	// TODO: handle exception
	System.out.println(" catch Block");
	int a = 10/0;
	
	return 10;
	}finally {
		System.out.println("finally Block :");
		return 15;
	}

	}
}
